### PR TITLE
feat(StringLiteral): Add support for embedded quotes in string literals

### PR DESCRIPTION
**Pull request by christopherthielen**
https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html#expressions-ref-literal

> Strings are delimited by single quotes. To put a single quote itself in a string, use two single quote characters.

### CODE REVIEW

**Comment by benmarch** [comment]
Thanks @christopherthielen!

**Comment by benmarch** [comment]
Released **0.2.3** with the changes.

**Comment by christopherthielen** [comment]
Nice! I have a couple more PRs I will submit next week. 

One to add template parsing and one to add typescript defs

**Comment by benmarch** [comment]
Awesome, thank you! I'm currently working on updating the dev stack, code, and README since I haven't touched this project in a couple years.

**Pull request merged**
